// <auto-generated />
using JobPortalCore.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobPortalCore.DAL.Migrations
{
    [DbContext(typeof(JobDbContext))]
    partial class JobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobPortalCore.Entity.Models.CandidateRegister", b =>
                {
                    b.Property<int>("Candidate_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mobNumber")
                        .HasColumnType("int");

                    b.HasKey("Candidate_Id");

                    b.ToTable("candidateRegister");
                });

            modelBuilder.Entity("JobPortalCore.Entity.Models.JobDetails", b =>
                {
                    b.Property<int>("Jobid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Companyname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Contactnumber")
                        .HasColumnType("int");

                    b.Property<string>("Contactperson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Joblocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jobtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technicalskills")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Jobid");

                    b.ToTable("job");
                });
#pragma warning restore 612, 618
        }
    }
}
